// packages/js/vue/src/Checkout.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import {
  createOpenReceiveVueCheckoutShellBinding,
  defineOpenReceiveElements,
  validateOpenReceiveWrapperCheckoutProps,
  type CheckoutShellOptions,
  type CheckoutSnapshot,
  type OpenReceiveThemePreference,
} from "./index.js";

defineOptions({
  name: "Checkout",
});

// Prop names, defaults, and per-mode applicability are the shared contract in
// docs/internal/wrapper-parity.md. Keep this list in step with it.
const props = withDefaults(
  defineProps<{
    // Snapshot mode: pass a `checkout` to render it directly.
    // Create mode: omit `checkout` and pass `orderId` (+ optional `prefix`); the underlying
    // <openreceive-checkout> element creates the checkout, then renders and polls itself.
    checkout?: CheckoutSnapshot;
    orderId?: string;
    prefix?: string;
    orderUrl?: string;
    paymentWizard?: boolean;
    decodeLinkUrl?: string;
    themeToggle?: boolean;
    defaultTheme?: OpenReceiveThemePreference;
    storageKey?: string;
    // Create mode only.
    metadata?: Record<string, unknown>;
    syncUrl?: boolean;
    resumePathPrefix?: string;
    routeOrderId?: string;
    onCopy?: (event: Event) => void;
    onOpenWallet?: (event: Event) => void;
    onState?: (event: Event) => void;
    onSettled?: (event: Event) => void;
    onProviderCopy?: (event: Event) => void;
    onStartOver?: (event: Event) => void;
    onError?: (event: Event) => void;
    options?: CheckoutShellOptions;
  }>(),
  {
    options: () => ({}),
    themeToggle: true,
  },
);

// Storage and matchMedia only exist in the browser: resolving the theme before mount
// would make a server-rendered shell disagree with the first client render.
const mounted = ref(false);
onMounted(() => {
  mounted.value = true;
  defineOpenReceiveElements();
});

const shell = computed(() => {
  validateOpenReceiveWrapperCheckoutProps({
    framework: "@openreceive/vue",
    checkout: props.checkout,
    orderId: props.orderId,
    metadata: props.metadata,
    syncUrl: props.syncUrl,
    resumePathPrefix: props.resumePathPrefix,
    routeOrderId: props.routeOrderId,
  });
  return createOpenReceiveVueCheckoutShellBinding(props.checkout ?? null, {
    ...props.options,
    themeToggle: props.themeToggle,
    deferThemeResolution: !mounted.value,
    ...(props.orderId === undefined ? {} : { orderId: props.orderId }),
    ...(props.prefix === undefined ? {} : { prefix: props.prefix }),
    ...(props.orderUrl === undefined ? {} : { orderUrl: props.orderUrl }),
    ...(props.paymentWizard === undefined ? {} : { paymentWizard: props.paymentWizard }),
    ...(props.decodeLinkUrl === undefined ? {} : { decodeLinkUrl: props.decodeLinkUrl }),
    ...(props.defaultTheme === undefined ? {} : { defaultTheme: props.defaultTheme }),
    ...(props.storageKey === undefined ? {} : { storageKey: props.storageKey }),
    ...(props.metadata === undefined ? {} : { metadata: props.metadata }),
    ...(props.syncUrl === undefined ? {} : { syncUrl: props.syncUrl }),
    ...(props.resumePathPrefix === undefined ? {} : { resumePathPrefix: props.resumePathPrefix }),
    ...(props.routeOrderId === undefined ? {} : { routeOrderId: props.routeOrderId }),
    ...(props.onCopy === undefined ? {} : { onCopy: props.onCopy }),
    ...(props.onOpenWallet === undefined ? {} : { onOpenWallet: props.onOpenWallet }),
    ...(props.onState === undefined ? {} : { onState: props.onState }),
    ...(props.onSettled === undefined ? {} : { onSettled: props.onSettled }),
    ...(props.onProviderCopy === undefined ? {} : { onProviderCopy: props.onProviderCopy }),
    ...(props.onStartOver === undefined ? {} : { onStartOver: props.onStartOver }),
    ...(props.onError === undefined ? {} : { onError: props.onError }),
  });
});
</script>

<template>
  <section v-bind="shell.rootAttributes">
    <component
      v-if="shell.themeToggle"
      :is="shell.themeToggle.tagName"
      v-bind="shell.themeToggle.attributes"
    />
    <component
      :is="shell.checkout.tagName"
      v-bind="shell.checkout.attributes"
      v-on="shell.checkout.listeners"
    />
  </section>
</template>

// packages/js/svelte/src/Checkout.svelte
<script lang="ts">
import { onMount } from "svelte";
import {
  createWrapperCheckoutShellBinding,
  defineElements,
  validateCheckoutProps,
  type CheckoutElementListeners,
  type CheckoutShellOptions,
  type CheckoutSnapshot,
  type ThemePreference,
} from "./index.js";

// Prop names, defaults, and per-mode applicability are the shared contract in
// docs/internal/wrapper-parity.md. This list RESTATES it because Svelte props
// are declarations, not a type: `export let` (and `let { … } = $props()` under
// runes) has to name every prop, so it cannot be derived from
// WrapperCheckoutComponentProps the way Vue's defineProps and
// React's CheckoutProps are. The duplication is forced, not neglected;
// tests/wrapper-parity.test.mjs is what keeps it in step.
// Snapshot mode: pass a `checkout` to render it directly.
// Create mode: omit `checkout` and pass `orderId` (+ optional `prefix`); the underlying
// <openreceive-checkout> element creates the checkout, then renders and polls itself.
export let checkout: CheckoutSnapshot | undefined = undefined;
export let orderId: string | undefined = undefined;
export let prefix: string | undefined = undefined;
export let paymentWizard: boolean | undefined = undefined;
export let decodeLinkUrl: string | undefined = undefined;
export let themeToggle: boolean | undefined = undefined;
export let defaultTheme: ThemePreference | undefined = undefined;
export let storageKey: string | undefined = undefined;
// Create mode only.
export let metadata: Record<string, unknown> | undefined = undefined;
export let syncUrl: boolean | undefined = undefined;
export let resumePathPrefix: string | undefined = undefined;
export let routeOrderId: string | undefined = undefined;
export let onCopy: ((event: Event) => void) | undefined = undefined;
export let onOpenWallet: ((event: Event) => void) | undefined = undefined;
export let onState: ((event: Event) => void) | undefined = undefined;
export let onSettled: ((event: Event) => void) | undefined = undefined;
export let onProviderCopy: ((event: Event) => void) | undefined = undefined;
export let onStartOver: ((event: Event) => void) | undefined = undefined;
export let onError: ((event: Event) => void) | undefined = undefined;
export let options: CheckoutShellOptions = {};

// Storage and matchMedia only exist in the browser: resolving the theme before mount
// would make a server-rendered shell disagree with the first client render.
let mounted = false;

onMount(() => {
  defineElements();
  mounted = true;
});

$: validateCheckoutProps({
  framework: "@openreceive/svelte",
  checkout,
  orderId,
  metadata,
  syncUrl,
  resumePathPrefix,
  routeOrderId,
});

$: shell = createWrapperCheckoutShellBinding(checkout ?? null, {
  ...options,
  themeToggle: themeToggle ?? options.themeToggle ?? true,
  deferThemeResolution: !mounted,
  ...(orderId === undefined ? {} : { orderId }),
  ...(prefix === undefined ? {} : { prefix }),
  ...(paymentWizard === undefined ? {} : { paymentWizard }),
  ...(decodeLinkUrl === undefined ? {} : { decodeLinkUrl }),
  ...(defaultTheme === undefined ? {} : { defaultTheme }),
  ...(storageKey === undefined ? {} : { storageKey }),
  ...(metadata === undefined ? {} : { metadata }),
  ...(syncUrl === undefined ? {} : { syncUrl }),
  ...(resumePathPrefix === undefined ? {} : { resumePathPrefix }),
  ...(routeOrderId === undefined ? {} : { routeOrderId }),
  ...(onCopy === undefined ? {} : { onCopy }),
  ...(onOpenWallet === undefined ? {} : { onOpenWallet }),
  ...(onState === undefined ? {} : { onState }),
  ...(onSettled === undefined ? {} : { onSettled }),
  ...(onProviderCopy === undefined ? {} : { onProviderCopy }),
  ...(onStartOver === undefined ? {} : { onStartOver }),
  ...(onError === undefined ? {} : { onError }),
});

// biome-ignore lint/correctness/noUnusedVariables: applied by the use: directive below, which biome does not read.
function checkoutListeners(node: HTMLElement, listeners: CheckoutElementListeners) {
  let activeListeners = listeners;

  const attach = () => {
    for (const [name, listener] of Object.entries(activeListeners)) {
      if (listener !== undefined) {
        node.addEventListener(name, listener);
      }
    }
  };
  const detach = () => {
    for (const [name, listener] of Object.entries(activeListeners)) {
      if (listener !== undefined) {
        node.removeEventListener(name, listener);
      }
    }
  };

  attach();

  return {
    update(nextListeners: CheckoutElementListeners) {
      detach();
      activeListeners = nextListeners;
      attach();
    },
    destroy() {
      detach();
    },
  };
}
</script>

<section {...shell.rootAttributes}>
  {#if shell.themeToggle}
    <svelte:element
      this={shell.themeToggle.tagName}
      {...shell.themeToggle.attributes}
    />
  {/if}
  <svelte:element
    this={shell.checkout.tagName}
    {...shell.checkout.attributes}
    use:checkoutListeners={shell.checkout.listeners}
  />
</section>
